// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameXsUserCoupon = "xs_user_coupon"

// XsUserCoupon 用户优惠券背包表
type XsUserCoupon struct {
	ID         uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        uint32 `gorm:"column:uid;not null;comment:用户UID" json:"uid"`                // 用户UID
	CouponID   uint32 `gorm:"column:coupon_id;not null;comment:优惠券id" json:"coupon_id"`    // 优惠券id
	Num        int32  `gorm:"column:num;not null;comment:数量" json:"num"`                   // 数量
	ExpireTime uint32 `gorm:"column:expire_time;not null;comment:过期时间" json:"expire_time"` // 过期时间
	Dateline   int64  `gorm:"column:dateline;not null;comment:创建时间" json:"dateline"`       // 创建时间
}

// TableName XsUserCoupon's table name
func (*XsUserCoupon) TableName() string {
	return TableNameXsUserCoupon
}
