// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameXsUserCouponLog = "xs_user_coupon_log"

// XsUserCouponLog 优惠券消耗记录表
type XsUserCouponLog struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        uint32 `gorm:"column:uid;not null;comment:用户UID" json:"uid"`                                             // 用户UID
	BigareaID  uint32 `gorm:"column:bigarea_id;not null;default:1;comment:用户大区ID" json:"bigarea_id"`                    // 用户大区ID
	CouponID   uint32 `gorm:"column:coupon_id;not null;comment:用户游戏优惠券" json:"coupon_id"`                               // 用户游戏优惠券
	Num        int32  `gorm:"column:num;not null;comment:数量" json:"num"`                                                // 数量
	Action     uint32 `gorm:"column:action;not null;comment:1 加， 2 减" json:"action"`                                    // 1 加， 2 减
	Op         uint32 `gorm:"column:op;not null;comment:1.下发，2.扣除,3.使用,4.过期,5.兑换,6.新人礼包下发,7.新人礼包过期,8.新人礼包删除" json:"op"` // 1.下发，2.扣除,3.使用,4.过期,5.兑换,6.新人礼包下发,7.新人礼包过期,8.新人礼包删除
	CouponType int32  `gorm:"column:coupon_type;not null;comment:优惠券类型，1.游戏优惠券" json:"coupon_type"`                     // 优惠券类型，1.游戏优惠券
	Reason     string `gorm:"column:reason;comment:扩展信息" json:"reason"`                                                 // 扩展信息
	Dateline   int64  `gorm:"column:dateline;primaryKey;comment:记录时间" json:"dateline"`                                  // 记录时间
}

// TableName XsUserCouponLog's table name
func (*XsUserCouponLog) TableName() string {
	return TableNameXsUserCouponLog
}
