// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	greeter2 "psl-layout/internal/biz/greeter"
	"psl-layout/internal/conf"
	"psl-layout/internal/data/greeter"
	"psl-layout/internal/server"
	"psl-layout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	greeterData, cleanup, err := greeter.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := greeter.NewGreeterRepo(greeterData, logger)
	greeterUsecase := greeter2.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
