// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"layout/internal/biz"
	"layout/internal/conf"
	"layout/internal/data"
	"layout/internal/pkg/registry"
	"layout/internal/server"
	"layout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	couponRepo := data.NewCouponRepo(dataData, logger)
	couponUsecase := biz.NewCouponUsecase(logger, couponRepo)
	couponGrpcService := service.NewCouponGrpcService(logger, couponUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, couponGrpcService, logger)
	httpServer := server.NewCouponGrpcMetricsHttpServer(bootstrap)
	consulRegistry := registry.NewConsulRegistry(bootstrap)
	app := newApp(logger, grpcServer, httpServer, consulRegistry)
	return app, func() {
		cleanup()
	}, nil
}
